"""init locations and observations

Revision ID: efab3558e41d
Revises: 
Create Date: 2026-02-28 12:09:49.650041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efab3558e41d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('weather_main', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('weather_desc', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('weather_icon', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('rain_1h', sa.Float(), nullable=True),
    sa.Column('snow_1h', sa.Float(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'observed_at', name='uq_observations_location_observed_at')
    )
    op.create_index(op.f('ix_observations_location_id'), 'observations', ['location_id'], unique=False)
    op.create_index('ix_observations_location_observed_at_desc', 'observations', ['location_id', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_observations_location_observed_at_desc', table_name='observations')
    op.drop_index(op.f('ix_observations_location_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_table('locations')
    # ### end Alembic commands ###
